### ISSUE TITLE
On using lokalise

### ISSUE THREAD

**Issue by onmyway133** [hyperoslo/ios-foundation#60]
As discussed in https://github.com/hyperoslo/ios-foundation/issues/15, we start using https://lokalise.co/projects for now.

When export, to avoid inconsistent changes, I think we should use these settings. What do you think?

- File format: Apple Strings (.strings, .stringsdict)
- Order keys by: Key name A-Z
- Data to export: All

![lokalise](https://cloud.githubusercontent.com/assets/2284279/23297915/ae034262-fa7b-11e6-8006-29ef66844a1f.png)

**Comment by zenangst** [comment]
Love the ordering keys thing, any other sorting would make my brain go 💣 💥

**Comment by onmyway133** [comment]
@zenangst yeah, I think we can close this for now
